name: .NET Core

on: [push]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v1
 
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test --configuration Release
